### ISSUE TITLE
Issue while installing for kibana 6.1.2

### ISSUE THREAD

**Issue by sanketpaga** [sasauz/kibana_vis_gantt#7]
Hi, 
Facing issue while installing plugin, below is the log
{"type":"log","@timestamp":"2018-03-05T10:06:33Z","tags":["info","optimize"],"pid":10908,"message":"Optimizing and caching bundles for graph, monitoring, ml, apm, kibana, stateSessionStorageRedirect, timelion, dashboardViewer and status_page. This may take a few minutes"}
{"type":"error","@timestamp":"2018-03-05T10:14:31Z","tags":["fatal"],"pid":10908,"level":"fatal","error":{"message":"Optimizations failure.\n   5850 modules\n    \n    \u001b[1m\u001b[31mERROR in ../plugins/gantt_vis/public/gantt_vis.js\n    Module not found: Error: Can't resolve 'ui/template_vis_type/template_vis_type' in 'C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\plugins\\gantt_vis\\public'\u001b[39m\u001b[22m\n    \n    \u001b[1m\u001b[31mERROR in ../plugins/gantt_vis/public/gantt_vis.js\n    Module not found: Error: Can't resolve 'ui/vis/schemas' in 'C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\plugins\\gantt_vis\\public'\u001b[39m\u001b[22m\n","name":"Error","stack":"Error: Optimizations failure.\n   5850 modules\n    \n    \u001b[1m\u001b[31mERROR in ../plugins/gantt_vis/public/gantt_vis.js\n    Module not found: Error: Can't resolve 'ui/template_vis_type/template_vis_type' in 'C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\plugins\\gantt_vis\\public'\u001b[39m\u001b[22m\n    \n    \u001b[1m\u001b[31mERROR in ../plugins/gantt_vis/public/gantt_vis.js\n    Module not found: Error: Can't resolve 'ui/vis/schemas' in 'C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\plugins\\gantt_vis\\public'\u001b[39m\u001b[22m\n\n    at FsOptimizer.failedStatsToError (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\src\\optimize\\base_optimizer.js:249:27)\n    at C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\src\\optimize\\fs_optimizer.js:37:30\n    at onCompiled (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\webpack\\lib\\Compiler.js:241:12)\n    at applyPluginsAsync.err (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\webpack\\lib\\Compiler.js:514:14)\n    at next (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:202:11)\n    at Compiler.<anonymous> (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\webpack\\lib\\CachePlugin.js:78:5)\n    at Compiler.applyPluginsAsyncSeries (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:206:13)\n    at compilation.seal.err (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\webpack\\lib\\Compiler.js:511:11)\n    at Compilation.applyPluginsAsyncSeries (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:195:46)\n    at self.applyPluginsAsync.err (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\webpack\\lib\\Compilation.js:671:19)\n    at Compilation.applyPluginsAsyncSeries (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:195:46)\n    at self.applyPluginsAsync.err (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\webpack\\lib\\Compilation.js:662:11)\n    at next (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:202:11)\n    at Compilation.<anonymous> (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\uglifyjs-webpack-plugin\\dist\\index.js:244:6)\n    at Compilation.applyPluginsAsyncSeries (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:206:13)\n    at self.applyPluginsAsync.err (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\webpack\\lib\\Compilation.js:657:10)\n    at next (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:202:11)\n    at Compilation.<anonymous> (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\extract-text-webpack-plugin\\dist\\index.js:275:11)\n    at Compilation.applyPluginsAsyncSeries (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:206:13)\n    at sealPart2 (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\webpack\\lib\\Compilation.js:653:9)\n    at next (C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:202:11)\n    at C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\node_modules\\extract-text-webpack-plugin\\dist\\index.js:244:13"},"message":"Optimizations failure.\n   5850 modules\n    \n    ERROR in ../plugins/gantt_vis/public/gantt_vis.js\n    Module not found: Error: Can't resolve 'ui/template_vis_type/template_vis_type' in 'C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\plugins\\gantt_vis\\public'\n    \n    ERROR in ../plugins/gantt_vis/public/gantt_vis.js\n    Module not found: Error: Can't resolve 'ui/vis/schemas' in 'C:\\MYSD_SOFTWARE\\ELK\\version_6_1_2\\kibana-6.1.2-windows-x86_64\\plugins\\gantt_vis\\public'\n"}

**Comment by chrisribe** [comment]
Got the same error for Kibana 6.4.2

**Comment by wkruse** [comment]
Kibana **6.x** doesn't seem to be supported yet, see #5.

**Comment by kaikaihsiang** [comment]
I got the same error for Kibana 6.5.4 too
